remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Wind and Wireless
description: Welcome to the home of Wind andwireless. Something something messages from magic pixies and 'the flies'.

show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]

---
---

@import "{{ site.theme }}";
